import "../styles/globals.css";
import type { Metadata } from "next";
import Header from "@/components/layouts/header";
import Footer from "@/components/layouts/footer";
import Providers from "@/providers/providers";
import { AuthProvider } from "@/providers/auth-provider";
import OfflineWrapper from "@/providers/offline-wrapper";

export const metadata: Metadata = {
  title: "Cyber E-Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
         <OfflineWrapper>
          <AuthProvider>
            <Header />
            {children}
            <Footer />
          </AuthProvider>
         </OfflineWrapper>
        </Providers>
      </body>
    </html>
  );
}
